USE [D:\AALIYAH GUTIERREZ\SOURCE\REPOS\DANS\DANS_CAFE\APP_DATA\DANSCAFEDB.MDF]

DROP TABLE IF EXISTS Cart;

-- Cart
CREATE TABLE Cart (
	UserName NVARCHAR(100) NOT NULL,
	prodID VARCHAR(10) NOT NULL,
	quantity INT NOT NULL,
	prodSize VARCHAR(25) NOT NULL,
	cartID VARCHAR(50) NOT NULL,
	FOREIGN KEY (prodID) REFERENCES Products(prodID),
	
);