USE [D:\AALIYAH GUTIERREZ\SOURCE\REPOS\DANS\DANS_CAFE\APP_DATA\DANSCAFEDB.MDF]

CREATE TABLE RegisteredUsers(
	Fname NVARCHAR(100) NOT NULL,
	Lname NVARCHAR(100) NOT NULL,
	UserName NVARCHAR(100) NOT NULL,
	Email NVARCHAR(100) NOT NULL,
	Password NVARCHAR(100) NOT NULL,
)